apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cd-kustomization-apps
  namespace: flux-system
resources:
  - ./overlays/main/
configMapGenerator:
  - name: helm-defaults
    files:
      - values.yaml=defaults.yaml
configurations:
  - kustomizeconfig.yaml

