apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sladk
  namespace: flux-system
spec:
  interval: 2h
  path: /fluxcd/apps/
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: sladk-repo
  targetNamespace: flux-system
  timeout: 3m0s
  wait: true
