apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sladk-main
  namespace: sladk

resources:
  - ../../base/
nameSuffix: -main
namespace: sladk
patches:
  - path: ./patch.yaml

