selectorLabels: |
  chartSelector
  blabla2
labels: |
  chart
  blabla
replcaCount: 1
rollingUpdate:
  maxSurge:
  maxUnavailable:
podAnnotations: {}
imagePullSecrets: {}
serviceAccountName: ""
image:
  pullPolicy:
  repository:
  tag:
livenessprobe: {}
startupprobe: {}
resources: {}
nodeSelector: {}
affinity: {}
tolerations: {}

hpaRequired: true
hpa:
  scaleDown:
    policies:
      percentPeriodSeconds: 15
      percentType: Percent
      percentValue: 100
    selectPolicy: Max
    stabilizationWindowSeconds: 300
  scaleUp:
    policies:
      podsPeriodSeconds: 15
      podsType: Pods
      podsValue: 4
      percentPeriodSeconds: 15
      percentType: Percent
      percentValue: 100
    selectPolicy: Max
    stabilizationWindowSeconds: 0
  maxReplicas: 1
  minReplicas: 1
  memory:
    averageUtilization: 90%
  cpu:
    averageUtilization: 90%
